### ISSUE TITLE
xform_function: resulting dataType of the DerivedField is always set to double

### ISSUE THREAD

**Issue by psxmc6** [SoftwareAG/r-pmml#5]
Hi,

First of all, I'd like to thank you for such a useful library.

I would like to ask about a specific attribute within _xform_function_ namely, **new_field_data_type**:

According to its signature below, it should be possible to define the data type of the newly derived variable:

```
xform_function(
  wrap_object,
  orig_field_name,
  new_field_name = "newField",
  new_field_data_type = "numeric",
  expression,
  map_missing_to = NA
)
```

However, when I set **new_field_data_type** attribute to "character" (tried with "string" too) it has no effect such that the resulting PMML snippet always contains **dataType = "double"** regardless of what I type in, and the following warning message appears:

`Warning message:
In '[<-.factor`(`*tmp*', ri, value = "character") :
  invalid factor level, NA generated`

**.pmmlLocalTransformations:**
---
```
244: else if (!is.na(inputs[fname, "xform_function"])) {
245:          origName <- inputs[fname, "orig_field_name"]
246:          missing <- inputs[fname, "missingValue"]
247:          dfNode <- xmlNode("DerivedField", attrs = c(name = fname, 
248:          dataType = "double", optype = "continuous"))
249:          funcNode <- .pmmlU(inputs[fname, "xform_function"])
250:          dfNode <- append.XMLNode(dfNode, funcNode)
251: }
```

Is there any straightforward workaround this issue other than manual correction?

My environment:
- R version 3.6.3
- pmml_2.4.0

Kind regards

**Comment by dbolotov** [comment]
Hello,

Thanks for pointing this out, it is indeed a bug spanning several functions. The implementation was meant to allow dataType "string" as well as "double". We will update the package; for now the quickest workaround would be manual correction.

Can you provide an example of a transformation you were interested in?

Thanks.

**Comment by psxmc6** [comment]
Hi,

Glad to hear it's going to be resolved.

I have basically a set of derived variables each being defined by some expression and essentially I would like to define the resulting data type for that newly produced field. Manual correction is not the way to go if we're dealing with > 100 variables, so this parameter would be a great help.

Kind regards

**Comment by dbolotov** [comment]
The latest update to master branch fixes `xform_function` to allow `new_field_data_type` to accept `"factor"` in addition to `"numeric"`. Factor variables from transformations are exported with `dataType = "string"` and `optype = "numeric"`, which is the same as for factor inputs that are not transformed. There is also a new example in the vignette where a factor variable is created from a numeric input. 

Please install from GitHub to get these changes, and let us know if this does not solve the issue.
