### ISSUE TITLE
Add modelVersion child node to header

### ISSUE THREAD

**Issue by FrieseWoudloper** [SoftwareAG/r-pmml#6]
Please add an extra optional argument to the `pmml` function for adding a `modelVersion` child node to the header of the PMML file.

**Comment by dbolotov** [comment]
Hello,
Thank you for your request. The PMML standard does allow for a modelVersion attribute in the Header: http://dmg.org/pmml/v4-4-1/Header.html. We will add an extra parameter to `pmml` in the next update. 

In the mean time, it is possible to insert modelVersion into an existing PMML by using `pmml::add_attributes`:

```
fit <- lm(Sepal.Length ~ ., data = iris[, -5])
fit_pmml <- pmml(fit)

fit_pmml <- add_attributes(fit_pmml, "/p:PMML/descendant::p:Header",
						attributes = c(modelVersion = "MODEL_VERSION"))
```

**Comment by dbolotov** [comment]
The latest updates to master branch add the parameter `model_version` to the `pmml()` function. This allows to set the `modelVersion` attribute in the PMML Header. Please install from github to get this change.
