### ISSUE TITLE
PMML version cannot be chosen

### ISSUE THREAD

**Issue by WilliamShakesBeer** [SoftwareAG/r-pmml#7]
Dear all,

I tried to save PMML files in R using the save_pmml(myModel, myFilename, version = X.Y) command.
The files are created, but no matter what I put behind "version =", I always get PMML version 4.4 output files.

This looks like a bug to me. Or am I making a mistake?

Best regards,
Will

**Comment by dbolotov** [comment]
Hello,

Apologies for late response. That is indeed a bug. The latest `r-pmml` package only exports models to PMML version 4.4.1 (the latest version), so the `version` parameter in `save_pmml()` has no bearing on the resulting PMML. We will remove it in a future update.
