### ISSUE TITLE
Multiple Models Support

### ISSUE THREAD

**Issue by nviets** [SoftwareAG/r-pmml#8]
Hello! Is there any plan to support [Multiple Models](http://dmg.org/pmml/v4-4/MultipleModels.html)? It would be useful to have built-in support for composing ensembles and segmentations from the model classes already supported in this package.

**Comment by dbolotov** [comment]
Hello,

Just to clarify, is your intention to combine different model types into one PMML file? For example, combining the predictions from a logistic regression and a neural net into one final prediction, all in one PMML?

Thanks.

**Comment by nviets** [comment]
I had in mind to combine models of the same type, e.g. a segmentation scheme consisting of several GLM models, but I believe Multiple Models supports any combination of types. Ensembling strategies are also supports in the specification.

**Comment by dbolotov** [comment]
Indeed, Multiple Models supports combinations of different model types. This is an interesting usecase, and in the past we have seen this done by stitching different model PMML files together by hand. We will add this to our roadmap, but sorry to say that we are not planning to work on this feature in the near future. Thanks.

**Comment by nviets** [comment]
Thanks for taking a look!
